# Generated by Django 2.2 on 2021-05-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='badass training grounds'),
            preserve_default=False,
        ),
    ]
